#!/usr/bin/env bash

# This script deploys the Flutter library to a public Flutter repo
# Parameters required
# $1 = repo branch e.g. "build/123"

if [ $# -ne 1 ]; then
  echo 1>&2 "$0: incorrect number arguments (expected 1: repo branch)"
  exit 2
fi

set -x
set -e

echo "Define github user"

git config --global user.name "iProov"
git config --global user.email "support@iproov.com"

# Clone the given branch in the private repo

git clone --branch master git@github.com:iProov/flutter-sdk.git src

echo "Determining Flutter-SDK version"

PROP_VALUE=$(cat "pubspec.yaml" | grep "version:" | cut -d':' -f2 | head -n 1)
PROP_VALUE=${PROP_VALUE//[\ \"]/}

#" <- IDE need to have this quote closed DOH!

echo "Flutter-SDK Version=$PROP_VALUE"

# Clone the public repo

echo "Cloning branch master in public repo"

git clone --branch master git@github.com:iProov/flutter.git dest

# Backup .git dir

mkdir tmp
cp -fR dest/.git tmp/
cp -fR dest/.gitignore tmp/

# Remove everything else from public clone

echo "Clear dest"

rm dest/.gitignore
rm -rf dest/.git
rm -rf dest/.idea
rm -rf dest/android/.idea
rm -rf dest/example/.idea
rm -rf dest/*

# Copy everything over

echo "Copy src to dest"
cp -fR src/* dest/
ls -lathr dest

# Remove things that shouldn't be there

echo "Remove unwanted dest files"
rm -rf dest/.git
rm -rf dest/.idea
rm -rf dest/android/.idea
rm -rf dest/example/.idea
rm dest/.gitignore
rm -rf dest/Scripts
rm dest/bitrise.yml
rm dest/iproov_sdk.iml

# These files need to be emptied

rm dest/pomdeps.gradle
touch dest/pomdeps.gradle

rm dest/owasp.gradle
touch dest/owasp.gradle

# Copy back .git

cp -fR tmp/.git dest/
cp -fR tmp/.gitignore dest/

# Commit back changes to public repo

echo "Commit public repo"

cd dest
echo "Create branch $1"
git checkout -b "$1"
git add -f --all
git status
echo "Commit"
git commit -am "Release Flutter-SDK $PROP_VALUE"
echo "Push"
git tag -f "v$PROP_VALUE"
git push -f --tags -u origin "$1"

cd -

# Tidy up

echo "Tidy up"

rm -rf tmp
rm -rf src
rm -rf dest
